#!/usr/bin/env python

import sys
import os
import json



if "__main__" in __name__:
    if len(sys.argv) == 3:
        numbers = map(int,sys.argv[1].split(','))
        myRegBalls = set(numbers[:5])
        myPwrBall = numbers[-1]
        jsonPath = sys.argv[2]
        if os.path.exists(jsonPath):
            history = json.load(open(jsonPath,'rb')).get("HISTORY",[])
            for cntr,pick in enumerate(history):
                regBalls = set(pick[0])
                pwrBall = pick[1]
                if pwrBall == myPwrBall and regBalls == myRegBalls:
                    print "you won on your {0} try!".format(cntr)
